SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH, COUNT(DISTINCT o.USER_ID) as PURCHASED_USERS, ROUND(COUNT(DISTINCT o.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) as PURCHASED_RATIO
FROM USER_INFO u
LEFT JOIN ONLINE_SALE o
ON u.USER_ID = o.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR, MONTH
HAVING YEAR IS NOT NULL
ORDER BY 1, 2
