WITH CODES AS(SELECT
             (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') as PY,
              (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') as C,
              (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') as FE
             )

SELECT CASE
    WHEN (SKILL_CODE & FE) AND (SKILL_CODE & PY) THEN 'A'
    WHEN (SKILL_CODE & C) THEN 'B'
    WHEN (SKILL_CODE & FE) THEN 'C'
        END AS GRADE, ID, EMAIL
FROM DEVELOPERS, CODES
WHERE SKILL_CODE & (FE + C)
ORDER BY 1, 2;
