WITH RECURSIVE cte (HOUR) AS
(
  SELECT 0
  UNION ALL
  SELECT HOUR + 1 FROM cte WHERE HOUR < 23
)
SELECT HOUR, COUNT(ANIMAL_ID)
FROM cte as c LEFT JOIN ANIMAL_OUTS as a ON c.HOUR = HOUR(a.DATETIME)
GROUP BY HOUR
ORDER BY HOUR;
